### ISSUE TITLE
Drag & drop doesn't work on Fedora 40 / Wayland

### ISSUE THREAD

**Issue by deusnovus** [x42/xjadeo#57] opened 2024-06-09 20:05 UTC
I'm currently working on a one-click Bitwig Studio / xjadeo sync situation, so while trying the latest xjadeo binary on Linux, I noticed that drag & drop doesn't seem to work.

I tried dragging .mp4 and .mov files right onto xjadeo's window and while the cursor displays a + sign, it yields nothing. Running it via terminal also does not display any additional information upon doing so.

Any suggestions would be graciously appreciated, thank you.

**Comment by x42** [comment] 2024-06-09 20:10
If I had to guess... it's likely an issue with XWayland.
Here on debian with Xorg DnD works.

Can you open a video using the context menu > File > Open Video (ctrl+o), or specifying it on the commandline?

**Comment by deusnovus** [comment] 2024-06-09 20:34
Yes, opening a video through the menu works great, no problem there!
This issue mostly pertains to the drag and drop feature.

Could this feature be implemented on XWayland?

**Comment by x42** [comment] 2024-06-09 20:55
I don't know. XWayland is supposed to be compatible with X11, yet searching the web for "Xwayland Drag Drop" finds a couple of issues and various applications are affected.

There are currently no plans to port xjadeo to wayland *wjadeo*. So if the issue is Xwayland specific (and not something else on Fedora 40 or your WM/system), it needs to be resolved by the XWayland team.

**Comment by deusnovus** [comment] 2024-06-10 07:47
I see... I also searched the web for "xwayland drag drop", but results vary on a case-to-case basis.

Are there any additional boot arguments I can include in my xjadeo.desktop, in order to force xjadeo to properly interact with xwayland?

I understand xjadeo is intended to work primarily with X11-based environments, so I really appreciate you taking the time to discuss Fedora and xwayland.

**Closed** 2024-06-10 09:26 UTC
